### ISSUE TITLE
Enhancements for References

### ISSUE THREAD

**Issue by atrancandoris** [SFDO-Tooling/Snowfakery#154]
Currently, the documentation states:

> The basic rule is that the last row (object) created with the nickname is the one that is referenced.

This may work for tight object hierarchies, however, it is not appropriate for loose connections of objects. It would be nice if we could just select an object type and specify the Id through existing randomization functionality.

Example:

| ObjectA.Id | ObjectB.Id | ObjectB.ObjectA.Id |
| ----------- | ---------- | ------------------ |
| 1           | 1          | 3                  |
| 2           | 2          |                    |
| 3           | 3          | 1                  |
| 4           | 4          |                    |

This is currently doable through nested objects, however it will always insert the object unless it is hidden (e.g., "__ObjectA"). This brings us to the next problem, which is that nested hidden objects are added as dependencies, breaking the mapping generator (circular reference warning, insert order not resolved). The mapper also uses the hidden object name as the table name, so the mapper does not work. For example:

  lookups:
    ObjectA:
      table: __ObjectA
      key_field: ObjectA

After looking at this issue for some time, I think just allowing the templates to take an Id instead of an object / nickname, and updating the generator could cover this use case. Thoughts?

**Comment by acrosman** [comment]
There is a related discussion at #125, and draft implementation of that proposal at #184.

**Comment by prescod** [comment]
@atrancandoris @acrosman 

Please let me know whether this is a good first step for what you need with respect to the references:

https://github.com/SFDO-Tooling/Snowfakery/pull/184/files#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R454

References to nicknames would be on the roadmap.

**Comment by atrancandoris** [comment]
will respond in #184
