### ISSUE TITLE
Indentation error in docs

### ISSUE THREAD

**Issue by joeblodgett** [SFDO-Tooling/Snowfakery#251]
In docs/index.md, the pet_stories.yml example has an error with the indentation. Snowfakery returns an error message when trying to parse the file.

Steps to reproduce:

- Copy the code for pet_stories.yml from docs/index.md. Save it to its own file.
- Run snowfakery pet_stories.yml

Error message:

```
An error occurred. If you would like to see a Python traceback, use the --debug-internals option.
Error: Unexpected key: cat
 near /Users/blodgett/Desktop/Snowfakery Test/pet_stories.yml:22
```

MacOS 10.13.6  
Snowfakery version 1.1.1

**Comment by joeblodgett** [comment]
@prescod I fixed this error in my own fork, but I don't know how to submit the pull request to you. I'm still figuring out GitHub.

**Comment by prescod** [comment]
Thanks Joe! I found your PR and pulled it over. The github UI can be quite confusing. Once someone else on my team reviews it, the change will become available quickly. Thanks!
