### ISSUE TITLE
Reduce frequency of docs builds?

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/Snowfakery#434]
At first glance, an eight minute build on each push seems wasteful. Did you consider only running a subset on `push` and the full build on commits to `main`? Or triggering when the commit touches one of these files?

_Originally posted by @jstvz in https://github.com/SFDO-Tooling/Snowfakery/pull/409#discussion_r661954441_

**Comment by jstvz** [comment]
Fixed in #460
