### ISSUE TITLE
Fake.PostalCode can generate 4 digit codes without leading zeroes (which are invalid)

### ISSUE THREAD

**Issue by dcinzona** [SFDO-Tooling/Snowfakery#479]
4 digit postal codes are invalid.  The generator should support leading zeroes.

https://github.com/joke2k/faker/blob/a565d46e928dba18938164de2125de1aabc3f825/faker/providers/address/en_US/__init__.py#L281

But `Faker` accounts for len==4
https://github.com/joke2k/faker/blob/a565d46e928dba18938164de2125de1aabc3f825/faker/providers/address/en_US/__init__.py#L386-L394

Unfortunately, I cannot tell if state_abbr is passed into the faker generator

**Comment by allisonletts** [comment]
This issue should be closed, I think 👍
