### ISSUE TITLE
getting STRING_TOO_LONG error when using 'fake: Username' in recipe

### ISSUE THREAD

**Issue by mirvinecx1** [SFDO-Tooling/Snowfakery#546]
When I use the following in a recipe:

```
- object: User
  fields:
    Username:
      fake: Username
```

and run with command:
` cci task run snowfakery --recipe snow/users.yml --org scratch_org`

I (frequently) get this error:

> [11/24/21 12:27:16] Running step: Insert User                                                                                                                                                      
> [11/24/21 12:27:17] Prepared 20 rows for DataOperationType.INSERT to User.                                                                                                                         
> 
> Error: Error on record with id 17: STRING_TOO_LONG: Username: data value too large: Candace_Vincent_74903c4d-2f2c-43f2-82d9-7f09a40c7bc5@laptop-20.williamson-velez.com (max length=80) (Username)
> 

And even though I get an error it still loads some data.
See screenshot with some data duplicated and some not, indicating the failed run loaded some data.
![Screenshot 2021-11-24 at 12 39 12](https://user-images.githubusercontent.com/88085251/143240255-64707a23-b826-4be5-aa05-a9ea3010764a.png)

**Comment by prescod** [comment]
Thanks for the report! This will be fixed in a Snowfakery release next week!
